name: ObjectTSaba
version: '1.0.0'
main: com.objectt.ObjectTSaba
api-version: '1.21'

permissions:
  objectt.default:
    default: true
    children:
      objectt.player: true
      objectt.home.add: true
      objectt.home.remove: true
      objectt.home.list: true
      objectt.home.use: true
      objectt.skull: true